// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// Generated by jnigen. Do not edit.

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `com.vanvixi.dir_picker.DirPicker$Companion`
extension type DirPicker$Companion._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class =
      jni$_.JClass.forName(r'com/vanvixi/dir_picker/DirPicker$Companion');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<DirPicker$Companion> type =
      $DirPicker$Companion$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory DirPicker$Companion(
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return _new$(_class.reference.pointer, _id_new$.pointer,
            _$defaultConstructorMarker.pointer)
        .object<DirPicker$Companion>();
  }
}

extension DirPicker$Companion$$Methods on DirPicker$Companion {
  static final _id_get$pickerHandler =
      DirPicker$Companion._class.instanceMethodId(
    r'getPickerHandler',
    r'()Lcom/vanvixi/dir_picker/PickerHandler;',
  );

  static final _get$pickerHandler = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final com.vanvixi.dir_picker.PickerHandler getPickerHandler()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? get pickerHandler {
    return _get$pickerHandler(reference.pointer, _id_get$pickerHandler.pointer)
        .object<jni$_.JObject?>();
  }

  static final _id_set$pickerHandler =
      DirPicker$Companion._class.instanceMethodId(
    r'setPickerHandler',
    r'(Lcom/vanvixi/dir_picker/PickerHandler;)V',
  );

  static final _set$pickerHandler = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void setPickerHandler(com.vanvixi.dir_picker.PickerHandler pickerHandler)`
  set pickerHandler(jni$_.JObject? pickerHandler) {
    final _$pickerHandler = pickerHandler?.reference ?? jni$_.jNullReference;
    _set$pickerHandler(reference.pointer, _id_set$pickerHandler.pointer,
            _$pickerHandler.pointer)
        .check();
  }

  static final _id_pick = DirPicker$Companion._class.instanceMethodId(
    r'pick',
    r'(ZLcom/vanvixi/dir_picker/PickerCallback;)V',
  );

  static final _pick = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_
                          .VarArgs<(jni$_.Int32, jni$_.Pointer<jni$_.Void>)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, core$_.int, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun pick(shouldPersist: kotlin.Boolean, callback: com.vanvixi.dir_picker.PickerCallback): kotlin.Unit`
  void pick(
    core$_.bool z,
    PickerCallback pickerCallback,
  ) {
    final _$pickerCallback = pickerCallback.reference;
    _pick(reference.pointer, _id_pick.pointer, z ? 1 : 0,
            _$pickerCallback.pointer)
        .check();
  }
}

final class $DirPicker$Companion$Type$
    extends jni$_.JType<DirPicker$Companion> {
  @jni$_.internal
  const $DirPicker$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/vanvixi/dir_picker/DirPicker$Companion;';
}

/// from: `com.vanvixi.dir_picker.DirPicker`
extension type DirPicker._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class =
      jni$_.JClass.forName(r'com/vanvixi/dir_picker/DirPicker');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<DirPicker> type = $DirPicker$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Lcom/vanvixi/dir_picker/DirPicker$Companion;',
  );

  /// from: `static public final com.vanvixi.dir_picker.DirPicker$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static DirPicker$Companion get Companion =>
      _id_Companion.get(_class, DirPicker$Companion.type)
          as DirPicker$Companion;

  static final _id_new$ = _class.constructorId(
    r'()V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory DirPicker() {
    return _new$(_class.reference.pointer, _id_new$.pointer)
        .object<DirPicker>();
  }

  static final _id_pick = _class.staticMethodId(
    r'pick',
    r'(ZLcom/vanvixi/dir_picker/PickerCallback;)V',
  );

  static final _pick = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_
                          .VarArgs<(jni$_.Int32, jni$_.Pointer<jni$_.Void>)>)>>(
          'globalEnv_CallStaticVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, core$_.int, jni$_.Pointer<jni$_.Void>)>();

  /// from: `static public final void pick(boolean z, com.vanvixi.dir_picker.PickerCallback pickerCallback)`
  static void pick(
    core$_.bool z,
    PickerCallback pickerCallback,
  ) {
    final _$pickerCallback = pickerCallback.reference;
    _pick(_class.reference.pointer, _id_pick.pointer, z ? 1 : 0,
            _$pickerCallback.pointer)
        .check();
  }
}

final class $DirPicker$Type$ extends jni$_.JType<DirPicker> {
  @jni$_.internal
  const $DirPicker$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/vanvixi/dir_picker/DirPicker;';
}

/// from: `com.vanvixi.dir_picker.PickerCallback`
extension type PickerCallback._(jni$_.JObject _$this) implements jni$_.JObject {
  static final _class =
      jni$_.JClass.forName(r'com/vanvixi/dir_picker/PickerCallback');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PickerCallback> type = $PickerCallback$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<core$_.int, $PickerCallback> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(
        0,
        descriptor.address,
        args.address,
      ),
    );
  }

  static final jni$_.Pointer<
          jni$_.NativeFunction<
              jni$_.JObjectPtr Function(
                  jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)>>
      _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onSuccess(Ljava/lang/String;)V') {
        _$impls[$p]!.onSuccess(
          ($a![0] as jni$_.JString),
        );
        return jni$_.nullptr;
      }
      if ($d == r'onCancelled()V') {
        _$impls[$p]!.onCancelled();
        return jni$_.nullptr;
      }
      if ($d == r'onError(Ljava/lang/String;Ljava/lang/String;)V') {
        _$impls[$p]!.onError(
          ($a![0] as jni$_.JString),
          ($a![1] as jni$_.JString),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $PickerCallback $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.vanvixi.dir_picker.PickerCallback',
      $p,
      _$invokePointer,
      [
        if ($impl.onSuccess$async) r'onSuccess(Ljava/lang/String;)V',
        if ($impl.onCancelled$async) r'onCancelled()V',
        if ($impl.onError$async)
          r'onError(Ljava/lang/String;Ljava/lang/String;)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory PickerCallback.implement(
    $PickerCallback $impl,
  ) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<PickerCallback>();
  }
}

extension PickerCallback$$Methods on PickerCallback {
  static final _id_onSuccess = PickerCallback._class.instanceMethodId(
    r'onSuccess',
    r'(Ljava/lang/String;)V',
  );

  static final _onSuccess = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun onSuccess(uri: kotlin.String): kotlin.Unit`
  void onSuccess(
    jni$_.JString string,
  ) {
    final _$string = string.reference;
    _onSuccess(reference.pointer, _id_onSuccess.pointer, _$string.pointer)
        .check();
  }

  static final _id_onCancelled = PickerCallback._class.instanceMethodId(
    r'onCancelled',
    r'()V',
  );

  static final _onCancelled = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public fun onCancelled(): kotlin.Unit`
  void onCancelled() {
    _onCancelled(reference.pointer, _id_onCancelled.pointer).check();
  }

  static final _id_onError = PickerCallback._class.instanceMethodId(
    r'onError',
    r'(Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _onError = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun onError(code: kotlin.String, message: kotlin.String): kotlin.Unit`
  void onError(
    jni$_.JString string,
    jni$_.JString string1,
  ) {
    final _$string = string.reference;
    final _$string1 = string1.reference;
    _onError(reference.pointer, _id_onError.pointer, _$string.pointer,
            _$string1.pointer)
        .check();
  }
}

abstract base mixin class $PickerCallback {
  factory $PickerCallback({
    required void Function(jni$_.JString string) onSuccess,
    core$_.bool onSuccess$async,
    required void Function() onCancelled,
    core$_.bool onCancelled$async,
    required void Function(jni$_.JString string, jni$_.JString string1) onError,
    core$_.bool onError$async,
  }) = _$PickerCallback;

  void onSuccess(jni$_.JString string);
  core$_.bool get onSuccess$async => false;
  void onCancelled();
  core$_.bool get onCancelled$async => false;
  void onError(jni$_.JString string, jni$_.JString string1);
  core$_.bool get onError$async => false;
}

final class _$PickerCallback with $PickerCallback {
  _$PickerCallback({
    required void Function(jni$_.JString string) onSuccess,
    this.onSuccess$async = false,
    required void Function() onCancelled,
    this.onCancelled$async = false,
    required void Function(jni$_.JString string, jni$_.JString string1) onError,
    this.onError$async = false,
  })  : _onSuccess = onSuccess,
        _onCancelled = onCancelled,
        _onError = onError;

  final void Function(jni$_.JString string) _onSuccess;
  final core$_.bool onSuccess$async;
  final void Function() _onCancelled;
  final core$_.bool onCancelled$async;
  final void Function(jni$_.JString string, jni$_.JString string1) _onError;
  final core$_.bool onError$async;

  void onSuccess(jni$_.JString string) {
    return _onSuccess(string);
  }

  void onCancelled() {
    return _onCancelled();
  }

  void onError(jni$_.JString string, jni$_.JString string1) {
    return _onError(string, string1);
  }
}

final class $PickerCallback$Type$ extends jni$_.JType<PickerCallback> {
  @jni$_.internal
  const $PickerCallback$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/vanvixi/dir_picker/PickerCallback;';
}
