// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `com.vanvixi.dir_picker.DirPicker$Companion`
class DirPicker$Companion extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<DirPicker$Companion> $type;

  @jni$_.internal
  DirPicker$Companion.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class =
      jni$_.JClass.forName(r'com/vanvixi/dir_picker/DirPicker$Companion');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<DirPicker$Companion?> nullableType =
      $DirPicker$Companion$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<DirPicker$Companion> type =
      $DirPicker$Companion$Type$();
  static final _id_getPickerHandler = _class.instanceMethodId(
    r'getPickerHandler',
    r'()Lcom/vanvixi/dir_picker/PickerHandler;',
  );

  static final _getPickerHandler = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final com.vanvixi.dir_picker.PickerHandler getPickerHandler()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getPickerHandler() {
    return _getPickerHandler(
            reference.pointer, _id_getPickerHandler as jni$_.JMethodIDPtr)
        .object<jni$_.JObject?>(const jni$_.$JObject$NullableType$());
  }

  static final _id_setPickerHandler = _class.instanceMethodId(
    r'setPickerHandler',
    r'(Lcom/vanvixi/dir_picker/PickerHandler;)V',
  );

  static final _setPickerHandler = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void setPickerHandler(com.vanvixi.dir_picker.PickerHandler pickerHandler)`
  void setPickerHandler(
    jni$_.JObject? pickerHandler,
  ) {
    final _$pickerHandler = pickerHandler?.reference ?? jni$_.jNullReference;
    _setPickerHandler(reference.pointer,
            _id_setPickerHandler as jni$_.JMethodIDPtr, _$pickerHandler.pointer)
        .check();
  }

  static final _id_pick = _class.instanceMethodId(
    r'pick',
    r'(ZLcom/vanvixi/dir_picker/PickerCallback;)V',
  );

  static final _pick = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_
                          .VarArgs<(jni$_.Int32, jni$_.Pointer<jni$_.Void>)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, int, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun pick(shouldPersist: kotlin.Boolean, callback: com.vanvixi.dir_picker.PickerCallback): kotlin.Unit`
  void pick(
    bool z,
    PickerCallback pickerCallback,
  ) {
    final _$pickerCallback = pickerCallback.reference;
    _pick(reference.pointer, _id_pick as jni$_.JMethodIDPtr, z ? 1 : 0,
            _$pickerCallback.pointer)
        .check();
  }

  static final _id_new$ = _class.constructorId(
    r'(Lkotlin/jvm/internal/DefaultConstructorMarker;)V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `synthetic public void <init>(kotlin.jvm.internal.DefaultConstructorMarker defaultConstructorMarker)`
  /// The returned object must be released after use, by calling the [release] method.
  factory DirPicker$Companion(
    jni$_.JObject? defaultConstructorMarker,
  ) {
    final _$defaultConstructorMarker =
        defaultConstructorMarker?.reference ?? jni$_.jNullReference;
    return DirPicker$Companion.fromReference(_new$(_class.reference.pointer,
            _id_new$ as jni$_.JMethodIDPtr, _$defaultConstructorMarker.pointer)
        .reference);
  }
}

final class $DirPicker$Companion$NullableType$
    extends jni$_.JType<DirPicker$Companion?> {
  @jni$_.internal
  const $DirPicker$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/vanvixi/dir_picker/DirPicker$Companion;';

  @jni$_.internal
  @core$_.override
  DirPicker$Companion? fromReference(jni$_.JReference reference) =>
      reference.isNull
          ? null
          : DirPicker$Companion.fromReference(
              reference,
            );
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<DirPicker$Companion?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DirPicker$Companion$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DirPicker$Companion$NullableType$) &&
        other is $DirPicker$Companion$NullableType$;
  }
}

final class $DirPicker$Companion$Type$
    extends jni$_.JType<DirPicker$Companion> {
  @jni$_.internal
  const $DirPicker$Companion$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/vanvixi/dir_picker/DirPicker$Companion;';

  @jni$_.internal
  @core$_.override
  DirPicker$Companion fromReference(jni$_.JReference reference) =>
      DirPicker$Companion.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<DirPicker$Companion?> get nullableType =>
      const $DirPicker$Companion$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DirPicker$Companion$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DirPicker$Companion$Type$) &&
        other is $DirPicker$Companion$Type$;
  }
}

/// from: `com.vanvixi.dir_picker.DirPicker`
class DirPicker extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<DirPicker> $type;

  @jni$_.internal
  DirPicker.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class =
      jni$_.JClass.forName(r'com/vanvixi/dir_picker/DirPicker');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<DirPicker?> nullableType =
      $DirPicker$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<DirPicker> type = $DirPicker$Type$();
  static final _id_Companion = _class.staticFieldId(
    r'Companion',
    r'Lcom/vanvixi/dir_picker/DirPicker$Companion;',
  );

  /// from: `static public final com.vanvixi.dir_picker.DirPicker$Companion Companion`
  /// The returned object must be released after use, by calling the [release] method.
  static DirPicker$Companion get Companion =>
      _id_Companion.get(_class, const $DirPicker$Companion$Type$());

  static final _id_new$ = _class.constructorId(
    r'()V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory DirPicker() {
    return DirPicker.fromReference(
        _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr)
            .reference);
  }

  static final _id_pick = _class.staticMethodId(
    r'pick',
    r'(ZLcom/vanvixi/dir_picker/PickerCallback;)V',
  );

  static final _pick = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_
                          .VarArgs<(jni$_.Int32, jni$_.Pointer<jni$_.Void>)>)>>(
          'globalEnv_CallStaticVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, int, jni$_.Pointer<jni$_.Void>)>();

  /// from: `static public final void pick(boolean z, com.vanvixi.dir_picker.PickerCallback pickerCallback)`
  static void pick(
    bool z,
    PickerCallback pickerCallback,
  ) {
    final _$pickerCallback = pickerCallback.reference;
    _pick(_class.reference.pointer, _id_pick as jni$_.JMethodIDPtr, z ? 1 : 0,
            _$pickerCallback.pointer)
        .check();
  }
}

final class $DirPicker$NullableType$ extends jni$_.JType<DirPicker?> {
  @jni$_.internal
  const $DirPicker$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/vanvixi/dir_picker/DirPicker;';

  @jni$_.internal
  @core$_.override
  DirPicker? fromReference(jni$_.JReference reference) => reference.isNull
      ? null
      : DirPicker.fromReference(
          reference,
        );
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<DirPicker?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DirPicker$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DirPicker$NullableType$) &&
        other is $DirPicker$NullableType$;
  }
}

final class $DirPicker$Type$ extends jni$_.JType<DirPicker> {
  @jni$_.internal
  const $DirPicker$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/vanvixi/dir_picker/DirPicker;';

  @jni$_.internal
  @core$_.override
  DirPicker fromReference(jni$_.JReference reference) =>
      DirPicker.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<DirPicker?> get nullableType => const $DirPicker$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($DirPicker$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($DirPicker$Type$) && other is $DirPicker$Type$;
  }
}

/// from: `com.vanvixi.dir_picker.PickerCallback`
class PickerCallback extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<PickerCallback> $type;

  @jni$_.internal
  PickerCallback.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class =
      jni$_.JClass.forName(r'com/vanvixi/dir_picker/PickerCallback');

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PickerCallback?> nullableType =
      $PickerCallback$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<PickerCallback> type = $PickerCallback$Type$();
  static final _id_onSuccess = _class.instanceMethodId(
    r'onSuccess',
    r'(Ljava/lang/String;)V',
  );

  static final _onSuccess = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun onSuccess(uri: kotlin.String): kotlin.Unit`
  void onSuccess(
    jni$_.JString string,
  ) {
    final _$string = string.reference;
    _onSuccess(reference.pointer, _id_onSuccess as jni$_.JMethodIDPtr,
            _$string.pointer)
        .check();
  }

  static final _id_onCancelled = _class.instanceMethodId(
    r'onCancelled',
    r'()V',
  );

  static final _onCancelled = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public fun onCancelled(): kotlin.Unit`
  void onCancelled() {
    _onCancelled(reference.pointer, _id_onCancelled as jni$_.JMethodIDPtr)
        .check();
  }

  static final _id_onError = _class.instanceMethodId(
    r'onError',
    r'(Ljava/lang/String;Ljava/lang/String;)V',
  );

  static final _onError = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public fun onError(code: kotlin.String, message: kotlin.String): kotlin.Unit`
  void onError(
    jni$_.JString string,
    jni$_.JString string1,
  ) {
    final _$string = string.reference;
    final _$string1 = string1.reference;
    _onError(reference.pointer, _id_onError as jni$_.JMethodIDPtr,
            _$string.pointer, _$string1.pointer)
        .check();
  }

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<int, $PickerCallback> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(
        0,
        descriptor.address,
        args.address,
      ),
    );
  }

  static final jni$_.Pointer<
          jni$_.NativeFunction<
              jni$_.JObjectPtr Function(
                  jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)>>
      _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onSuccess(Ljava/lang/String;)V') {
        _$impls[$p]!.onSuccess(
          $a![0]!.as(const jni$_.$JString$Type$(), releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
      if ($d == r'onCancelled()V') {
        _$impls[$p]!.onCancelled();
        return jni$_.nullptr;
      }
      if ($d == r'onError(Ljava/lang/String;Ljava/lang/String;)V') {
        _$impls[$p]!.onError(
          $a![0]!.as(const jni$_.$JString$Type$(), releaseOriginal: true),
          $a![1]!.as(const jni$_.$JString$Type$(), releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $PickerCallback $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.vanvixi.dir_picker.PickerCallback',
      $p,
      _$invokePointer,
      [
        if ($impl.onSuccess$async) r'onSuccess(Ljava/lang/String;)V',
        if ($impl.onCancelled$async) r'onCancelled()V',
        if ($impl.onError$async)
          r'onError(Ljava/lang/String;Ljava/lang/String;)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory PickerCallback.implement(
    $PickerCallback $impl,
  ) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return PickerCallback.fromReference(
      $i.implementReference(),
    );
  }
}

abstract base mixin class $PickerCallback {
  factory $PickerCallback({
    required void Function(jni$_.JString string) onSuccess,
    bool onSuccess$async,
    required void Function() onCancelled,
    bool onCancelled$async,
    required void Function(jni$_.JString string, jni$_.JString string1) onError,
    bool onError$async,
  }) = _$PickerCallback;

  void onSuccess(jni$_.JString string);
  bool get onSuccess$async => false;
  void onCancelled();
  bool get onCancelled$async => false;
  void onError(jni$_.JString string, jni$_.JString string1);
  bool get onError$async => false;
}

final class _$PickerCallback with $PickerCallback {
  _$PickerCallback({
    required void Function(jni$_.JString string) onSuccess,
    this.onSuccess$async = false,
    required void Function() onCancelled,
    this.onCancelled$async = false,
    required void Function(jni$_.JString string, jni$_.JString string1) onError,
    this.onError$async = false,
  })  : _onSuccess = onSuccess,
        _onCancelled = onCancelled,
        _onError = onError;

  final void Function(jni$_.JString string) _onSuccess;
  final bool onSuccess$async;
  final void Function() _onCancelled;
  final bool onCancelled$async;
  final void Function(jni$_.JString string, jni$_.JString string1) _onError;
  final bool onError$async;

  void onSuccess(jni$_.JString string) {
    return _onSuccess(string);
  }

  void onCancelled() {
    return _onCancelled();
  }

  void onError(jni$_.JString string, jni$_.JString string1) {
    return _onError(string, string1);
  }
}

final class $PickerCallback$NullableType$ extends jni$_.JType<PickerCallback?> {
  @jni$_.internal
  const $PickerCallback$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/vanvixi/dir_picker/PickerCallback;';

  @jni$_.internal
  @core$_.override
  PickerCallback? fromReference(jni$_.JReference reference) => reference.isNull
      ? null
      : PickerCallback.fromReference(
          reference,
        );
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PickerCallback?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PickerCallback$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PickerCallback$NullableType$) &&
        other is $PickerCallback$NullableType$;
  }
}

final class $PickerCallback$Type$ extends jni$_.JType<PickerCallback> {
  @jni$_.internal
  const $PickerCallback$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/vanvixi/dir_picker/PickerCallback;';

  @jni$_.internal
  @core$_.override
  PickerCallback fromReference(jni$_.JReference reference) =>
      PickerCallback.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<PickerCallback?> get nullableType =>
      const $PickerCallback$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($PickerCallback$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($PickerCallback$Type$) &&
        other is $PickerCallback$Type$;
  }
}
