import 'dart:io';

import 'package:jnigen/jnigen.dart';

void main(List<String> args) async {
  final packageRoot = Platform.script.resolve('../');

  await generateJniBindings(
    Config(
      outputConfig: OutputConfig(
        dartConfig: DartCodeOutputConfig(
          path: packageRoot.resolve('lib/src/platforms/android/native.g.dart'),
          structure: OutputStructure.singleFile,
        ),
      ),
      androidSdkConfig: AndroidSdkConfig(
        addGradleDeps: true,
        addGradleSources: true,
        androidExample: 'example/',
      ),
      sourcePath: [
        packageRoot.resolve('android/src/main/kotlin/com/vanvixi/dir_picker/'),
      ],
      classes: [
        'com.vanvixi.dir_picker.DirPicker',
        'com.vanvixi.dir_picker.PickerCallback',
      ],
      preamble: '// Generated by jnigen. Do not edit.\n',
    ),
  );
}
