// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Bindings for Darwin (iOS/macOS) `dir_picker_ffi.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class DirPickerBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  DirPickerBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  DirPickerBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  /// Initialize Dart API for NativePort communication.
  /// Must be called before using dir_picker_pick.
  ///
  /// @param data Pointer from NativeApi.initializeApiDLData
  /// @return 0 on success, -1 on failure
  int dir_picker_init_dart_api_dl(
    ffi.Pointer<ffi.Void> data,
  ) {
    return _dir_picker_init_dart_api_dl(
      data,
    );
  }

  late final _dir_picker_init_dart_api_dlPtr =
      _lookup<ffi.NativeFunction<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>>(
          'dir_picker_init_dart_api_dl');
  late final _dir_picker_init_dart_api_dl = _dir_picker_init_dart_api_dlPtr
      .asFunction<int Function(ffi.Pointer<ffi.Void>)>();

  /// Show a directory picker dialog and report the result via NativePort.
  ///
  /// Messages sent to native_port:
  /// - Success:    [0, directoryUri]
  /// - Cancelled:  [1]
  /// - Error:      [2, errorCode, errorMessage]
  ///
  /// @param native_port Dart NativePort for result reporting
  /// @param prompt      Label for the confirmation button (macOS only, nullable)
  /// @param message     Descriptive text in the panel (macOS only, nullable)
  void dir_picker_pick(
    int native_port,
    ffi.Pointer<ffi.Char> prompt,
    ffi.Pointer<ffi.Char> message,
  ) {
    return _dir_picker_pick(
      native_port,
      prompt,
      message,
    );
  }

  late final _dir_picker_pickPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Char>)>>('dir_picker_pick');
  late final _dir_picker_pick = _dir_picker_pickPtr.asFunction<
      void Function(int, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>();
}
